// Interface automatically generated by schemas-to-ts

import { Category } from '../../../category/content-types/category/category';
import { Category_Plain } from '../../../category/content-types/category/category';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Restaurant {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    description?: string;
    categories?: { data: Category[] };
  };
}
export interface Restaurant_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  categories?: Category_Plain[];
}

export interface Restaurant_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  categories?: number[];
}

export interface Restaurant_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  description?: string;
  categories?: AdminPanelRelationPropertyModification<Category_Plain>[];
}
